### ISSUE TITLE
you didn't package the pom.xml with the maven project

### ISSUE THREAD

**Issue by ghost** [Jonatino/Abendigo-Offset-Scanner#2]
if i'm not mistaken this is a maven driven project (see: file hierarchy)  
just incase you didn't know, the pom.xml is pretty important for a maven project, especially if you want to compile using maven (which, by the way, makes everything much simpler for contributors)

**Comment by ghost** [comment]
nevermind it's gradle ignore me ;-;

**Comment by jonatino** [comment]
I will be switching it to maven soon. it has better support in intellij
